### ISSUE TITLE
Dependency Injection in Presentation Model

### ISSUE THREAD

**Issue by roshanpisharody** [dmdevgo/RxPM#28]
How will you go about Injecting PresentationModel through an dependecy Injector? then pass to the overriden provide method?

**Comment by Jeevuz** [comment]
Most of the time we "get" the PM from the DI container right in the provide method. But injecting it in a separate variable and then provide it is valid too. But we don't need this variable after it is provided, so we just preffer the firts variant. Anyway, It's up to you how to provide the PM.

**Comment by roshanpisharody** [comment]
That makes sense. Thanks.
