### ISSUE TITLE
Unnecessary rxjava operator call

### ISSUE THREAD

**Issue by aasitnikov** [dmdevgo/RxPM#31]
While i was looking through source code of PmExtensions.kt, i noticed that on 115 line there's identity call: .flatMapIterable { it }. I think you can safely replace previous method in call chain(map { }) with flatMapIterable without hurting readability and improve runtime performance a bit.
Also in skipWhileInProgress last two methods use .first and .second properties of Pair, while bufferWhileIdle use destructing declaration for same purposes, which serves better readabily.

**Comment by dmdevgo** [comment]
Thanks for the review, you can open a pull request
