### ISSUE TITLE
Make relay and consumer in PresentationModel protected or public 

### ISSUE THREAD

**Issue by nikiJava** [dmdevgo/RxPM#34]
Sometimes there is need to create custom control (for example, for Spinner) and there is a problem with `relay` in `PresentationModel` - it's `internal` and there is no way to write custom control cause `relay` visible only to the library package. There is the same problem with `consumer` - it's visible only to the `PresentationModel`.

**Comment by dmdevgo** [comment]
This will break the state encapsulation. And there will be a temptation to change the state in the view. Encapsulation is the main reason that the `relay` is wrapped in `State`. 
I think it would be better to make `BaseControl` and provide access only inside the control.

**Comment by dmdevgo** [comment]
Problem resolved in version 2.0
For version 1.x use a child PM to implement custom controls.
