### ISSUE TITLE
Navigation message observable lifecycle

### ISSUE THREAD

**Issue by sdelaysam** [dmdevgo/RxPM#35]
Kinda question which may be a bug
```
fun onCreate() {
 navigationMessagesDisposable = presentationModel.navigationMessages.observable
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe {
                navigationMessagesDispatcher.dispatch(it)
            }
}

fun onDestroy() {
navigationMessagesDisposable.dispose()
}
```

Posting navigation messages which commit fragment transactions may lead to 
```
 Can not perform this action after onSaveInstanceState
```
Or I'm missing something?

**Comment by dmdevgo** [comment]
The property `navigationMessages` is a`Command`, it buffer values while a View unbound from PresentationModel. So, despite that the subscription is alive, messages will not be delivered to the subscriber until the view is binded to the PresentationModel.
There is a [test](https://github.com/dmdevgo/RxPM/blob/33c7ae010d7051778260339c5180640b586bc24a/rxpm/src/test/kotlin/me/dmdev/rxpm/PresentationModelTest.kt#L117) for this case:
```
    @Test fun commandBlocksItemsAfterUnbinded() {
        val testObserver = pm.commands.observable.test()

        pm.lifecycleConsumer.accept(CREATED)
        pm.lifecycleConsumer.accept(BINDED)
        pm.lifecycleConsumer.accept(UNBINDED)
        pm.acceptCommand(1)

        testObserver.assertEmpty()
    }
```

**Comment by sdelaysam** [comment]
I see and it must work as you describe..
I faced that crash on the test project I made.
Appreciate If you can point out the issue on my side if any
```
class TestActivity : PmSupportActivity<TestActivityPm>(), NavigationMessageHandler {

    override fun providePresentationModel() = TestActivityPm()

    override fun onBindPresentationModel(pm: TestActivityPm) {}

    override fun handleNavigationMessage(message: NavigationMessage): Boolean {
        when (message) {
            is NavigationCommand ->
                supportFragmentManager.beginTransaction()
                        .replace(R.id.container, TestFragment())
                        .commit()
        }
        return true
    }
}

class TestActivityPm : PresentationModel() {

    override fun onUnbind() {
        super.onUnbind()
        navigationMessages.consumer.accept(NavigationCommand())
    }
}

class NavigationCommand : NavigationMessage
```

Log gives the following
```
TestActivity, onCreate
TestActivityPm, onBind
TestActivity, onStart
TestActivityPm, onUnbind
TestActivity, onStop
TestActivity, handleNavigationMessage

Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
```

I'm on latest develop branch and `PresentationModelTest` all passed.

**Comment by sdelaysam** [comment]
Please check if the fix is appropriate

**Comment by dmdevgo** [comment]
You're right, the bug is reproduced.

**Comment by sdelaysam** [comment]
@dmdevgo sorry but another related issue.
Same setup, only difference
```
class TestActivityPm : PresentationModel() {

    override fun onBind() {
        super. onBind()
        navigationMessages.consumer.accept(NavigationCommand())
    }
}
```
Android studio starts the launcher activity when device is idle and log is the same.
```
TestActivity, onCreate
12:44:18.848 TestActivityPm, onBind
12:44:18.850 TestActivity, onStart
12:44:18.889 TestActivityPm, onUnbind
12:44:18.892 TestActivity, onStop
12:44:18.895 TestActivity, handleNavigationMessage
```

The "issue" seems to be here
```
navigationMessagesDisposable = presentationModel.navigationMessages.observable
            .observeOn(AndroidSchedulers.mainThread()) <--- 
            .subscribe {
                navigationMessagesDispatcher.dispatch(it)
            }
```

Associated looper decide to execute dispatch on the next frame while with `Schedulers.trampoline()` it works fine.

Not sure its library issue - most likely its not real-life scenario.

**Comment by dmdevgo** [comment]
@sdelaysam why the view unbind immediately after binding? Can you describe more details?

**Comment by sdelaysam** [comment]
I just noticed that issue when build and run the app on device (device was idle) via Android Studio.
onStart/onStop called almost instantly ( in less than 50ms according to the timing )

PS: I think it can be ignored because
> most likely its not real-life scenario.

**Comment by dmdevgo** [comment]
First issue has been fixed. Second case is not reproduced from me. So I close issue.
