### ISSUE TITLE
In fragment onBindPresentationModel calls before onViewCreated

### ISSUE THREAD

**Issue by vchernyshov** [dmdevgo/RxPM#43]
onViewCreated often uses to initialize views via findViewById but in version 2.0 this initialization should be done or in onCreateView or call initialization code before super. onViewCreated. I guess this changes can broke a lot code after updating to new version and overriding onCreateView not so convenient as onViewCreated.

Maybe there is some way to return previous behavior?

**Comment by dmdevgo** [comment]
I propose to bind in `onActivityCreated`, it is called after `onViewCreated`.
