### ISSUE TITLE
Make onCreate(), onDestroy(), onBind(), onUnbind() @CallSuper

### ISSUE THREAD

**Issue by domisafonova** [dmdevgo/RxPM#44]
CallSuper is applied to framework lifecycle methods on activities and fragments.  It also applies transitively to their subclasses in jetpack/support library.  Using CallSuper on lifecycle methods in UI code may be considered a convention at that point.
I find RxPM's behavior a little conuterintuitive, because the lack of CallSuper on a method is basically a hint to omit a super call.  That led to some hard to find bugs when trying out RxPM at my workplace.  The issue was solved by using an application-wise BasePresentationModel with the annotation, but it still caused some confusion.

**Comment by dmdevgo** [comment]
@dmnsafonov Thanks for the suggestion. Basic lifecycle callbacks in the PM, such as onCreate or onBind, have an empty body and therefore do not need to call the super method.
