### ISSUE TITLE
Method onBindPresentationModel not call

### ISSUE THREAD

**Issue by wpbloger** [dmdevgo/RxPM#45]
In the normal case, everything works and the method is called.
But specifically in my case, I have a FragmentStatePagerAdapter where there are identical fragments that are attached to the presenter model and when you scroll through the fragments, some are properly destroyed to save resources, and when you switch to the fragment that was previously destroyed, the onBindPresentationModel method is no longer called, and I have to bind in the onActivityCreated method

**Comment by dmdevgo** [comment]
@wpbloger What version of RxPM and Support Library are you using?
Could you please provide any logs or sample to reproduced the problem.

**Comment by wpbloger** [comment]
I am using version 2.0
In fact, logs are not needed here, I do not use any other architectural libraries, the usual android fragments that inherit PmFragment.
In this case, all methods of the fragment are called, such as onCreate, onViewCreated, but method onBindPresentationModel not called.
I tested on emulator with api 29.
@dmdevgo try the same little test with the FragmentStatePagerAdapter, I think you will have the same.

**Comment by dmdevgo** [comment]
@wpbloger Your problem is not reproduced for me. See branch with a sample.

**Comment by wpbloger** [comment]
@dmdevgo This is strange, but it reproduces for me.
I did not run your code, but I wrote a small example in which the method is not called, download and run on the emulator with api 29 (I started from it).
As I checked, we see that first onBindPresentationModel lines are written to the log, then when they are scrolled, fragments are deleted and the onDestroy records are displayed in the log, and if you then return to the deleted fragments and log entries are no longer written
[https://yadi.sk/d/tZrzgEj8bGfPXA](https://yadi.sk/d/tZrzgEj8bGfPXA)
Maybe I'm doing something wrong?

**Comment by dmdevgo** [comment]
@wpbloger In the sample that you sent, you are trying to reuse fragments that have already been destroyed. As you scroll to the right, the fragments are destroyed, but they are still cached in your list. Therefore, when you scroll to the left again, you give the destroyed fragment to the pager. There is no need to store fragments in the list, you must create the fragment when it is requested by the pager.

**Comment by wpbloger** [comment]
@dmdevgo Yes, you're right, it seems I have not figured out the documentation for the FragmentStatePagerAdapter, now everything is fine and the method is called as it should.
Thanks for the clarification.
