### ISSUE TITLE
How can I unset State?

### ISSUE THREAD

**Issue by gumam** [dmdevgo/RxPM#55]
In a project I need unset state<SomeObject> when user logout. How can I do it?

**Comment by Jeevuz** [comment]
IMO, the easiest way is to use sealed classes like this:
```kotlin
sealed class Value

data class Some(val value): Value

object Empty: Value
```

and pass Empty when you need to "unset" your state.

**Comment by gumam** [comment]
It resolves my problem. Thank you.
