### ISSUE TITLE
Testing Command<T> in RxPm PresentationModel

### ISSUE THREAD

**Issue by toxyduck** [dmdevgo/RxPM#56]
Hi, I want to test my PresentationModel and have the problem with `Command`.
Thats my test
```
@Test
    fun `sign in clicked`() {
        pm.signInClicks.consumer.accept(Unit)
        pm.navigationMessages.observable.test().assertValue { it is AppNavigationMessages.SignInOpen }
    }
```
I noticed that the command depends on the Android Schedulers if the buffer is not zero. I do not want to inject a command to PresentationModel for more readable Pm constructor. What's best practices to test commands in RxPm?

**Comment by Jeevuz** [comment]
Hi! We have small block in readme about testing. It mentions PmTestHelper. Command depends to the lifecycle of PM and only emit items in the binded state. So the PmTestHelper will help you to set lifecycle to that state before you assert.

**Comment by Jeevuz** [comment]
Also you need some rule for schedullers. See https://github.com/dmdevgo/RxPM/blob/develop/rxpm/src/test/kotlin/me/dmdev/rxpm/util/SchedulersRule.kt

**Comment by toxyduck** [comment]
Thanks!
