### ISSUE TITLE
About Conductor Support

### ISSUE THREAD

**Issue by brcbydr** [dmdevgo/RxPM#60]
Hi all, 

FOA thanks for the library.

I am trying to implement RxPM with Conductor. But getting "public final class TestBaseFormController extends me.dmdev.rxpm.base.PmController<com.xxx.xx.presentationmodels.FormValidationPm> { class file for com.bluelinelabs.conductor.RestoreViewOnCreateController not found" error.

My steps:

- Added implementation 'me.dmdev.rxpm:rxpm:2.1' to build.gradle and synced.

- Created FormValidationPm class like the sample app.

- Created Controller like below:

`
class BaseFormController : PmController<FormValidationPm>() {

    override fun providePresentationModel(): FormValidationPm {
        return FormValidationPm()
    }

    override fun onBindPresentationModel(pm: FormValidationPm) {
        TODO("Not yet implemented")
    }

}
`

Please let me know if it is not working with Conductor. 

Thanks in advance!

**Comment by dmdevgo** [comment]
@brcbydr Have you added Conductor dependency?

**Comment by brcbydr** [comment]
Sure, I am working with Conductor already. Trying to implement RxPM.

17 Tem 2020 Cum 20:02 tarihinde Dmitriy Gorbunov <notifications@github.com>
şunu yazdı:

**Comment by dmdevgo** [comment]
It seems `RestoreViewOnCreateController` has been [removed](https://github.com/bluelinelabs/Conductor/commit/4c9f2e9f307bbf33ade8305246f8320493a78d36).
As a workaround, you can create your `PmController` using `PmControllerDelegate`.

**Comment by dmdevgo** [comment]
Fixed in [2.1.1](https://github.com/dmdevgo/RxPM/releases/tag/v2.1.1)

**Comment by brcbydr** [comment]
Thank you for your quick fix. I am very appreciate it.
It is working great now. 

Just wanted to ask one more question about Conductor and RxPM: I have a navigator and router push the related controllers there. And I pass the model as a parameter for controllers.
I think I can implement two way binding using RxPM and can find a better solution about passing model using RxPM again. Please let me know if you have any idea about that I want to know best practise.

Thanks again!

**Comment by dmdevgo** [comment]
The best solution would be to use the repository pattern and Сlean Architecture. Instead of passing the model, it is better to pass the ID and retrieve the model from the repository by ID.

There is two way binding in RxPM, for example, you can use `InputControl` and `CheckControl` to bind to `EditText` and `CheckBox`. Also, you can create your controls in the same way.

**Comment by brcbydr** [comment]
Thanks again @dmdevgo !

I have implemented RxPM validation to all my app's pages. But realized that when form is valid and errors cleaned, button click not working :( If onBindPresentationModel not triggered, button click working well.

It is very important to go on with RxPM for me now. Please let me know the problem. Am I missing sth or is it Conductor issue? 

`abstract class BaseFormController(bundle: Bundle? = null) : PmController<FormValidationPm>(bundle) {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup, savedViewState: Bundle?): View {
        ....
    }

    override fun providePresentationModel(): FormValidationPm {
        return FormValidationPm()
    }
}`

`class RegisterVerificationController(bundle: Bundle) : BaseFormController(bundle) {

    constructor(model: Person) : this(Bundle().apply {
        putParcelable(PERSON, model)
    })

    // Access arguments
    private val model by lazy {
        args.getParcelable<Person>(PERSON) as Person
    }

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup, savedViewState: Bundle?): View {
        val view = inflater.inflate(R.layout.controller_register_verification, container, false)

        view.button_verification.setOnClickListener {
            /*NOT CALLING IF onBindPresentationModel NOT IMPLEMENT*/
        }

        return view
    }

    override fun onBindPresentationModel(pm: FormValidationPm) {
        view?.run {
            pm.verificationCode bindTo this.edit_text_verification_code

            pm.termsCheckBox bindTo this.checkbox_user_agreement
            pm.acceptTermsOfUse bindTo {
                Toast.makeText((activity as AppCompatActivity), it, Toast.LENGTH_SHORT).show()
            }
            this.button_verification.clicks() bindTo pm.validateButtonClicks
        }
    }
}`

Thanks in advance!

**Comment by dmdevgo** [comment]
Obviously, in `onBindPresentationModel` you overwrite the button click listener. This line:
`this.button_verification.clicks() bindTo pm.validateButtonClicks`
If you no longer have problems with the Conductor, can I close this issue? 
If you have any questions about working with RxPM, please, open another issue.

**Comment by brcbydr** [comment]
Of course you are right, my problem is not about overridden ui listeners, how can trigger onAcitivityResult in pm class etc. Anyway thanks for your support again.
